### ISSUE TITLE
Makefile compiler errors

### ISSUE THREAD

**Issue by zachchanak** [wchen329/class#2]
I tried making CLASS on the cae linux machines and the cs linux machines and am getting this error. 

![make_error](https://user-images.githubusercontent.com/47953007/112081112-2556f600-8b51-11eb-958c-dbde4338d439.PNG)

**Comment by wchen329** [comment]
Ah, it appears that may be because cstddef (or whatever header that declares ptrdiff_t, maybe cstdint) probably was included in some other header I used on a newer version of GCC but isn't declared in the corresponding header on the CAE machines' GCC. Thanks for reporting this, I will go add the header, and link the corresponding PR in this issue when I've fixed it.

**Comment by wchen329** [comment]
BTW if you have the most recent snapshot of the master branch it will only compile CLASS all the way even when this is resolved, and not CLOAD as it links with various libraries from the Intel OPAE SDK.

To build CLOAD you have to build it on Intel DevCloud or install the OPAE locally.

**Comment by wchen329** [comment]
Hmm, it appears I've forgot to actually make a new branch.

No matter, I've directly committed to master. I was able to build CLASS on CAE just now. CLOAD should be built on DevCloud when possible (you can however, build the dumb version of the loader after I cherry pick that commit back to the "dumb-loader" branch).

Commit which fixes it:
ab6041105b648c85161cde4cd15f6fcda28a334f

Please remember to pull, and thanks!

Marking as resolved.

**Comment by wchen329** [comment]
Reopen: It looks like this "ptrdiff_t" issue is common with other files as well, so I'm going to keep this open until I've pushed the necessary commits to "dumb-cload," CLASS does not have this issue, but apparently some part of CLOAD do.

**Comment by wchen329** [comment]
Fixed, mmem.h was the only other file that had this issue.

Marking as resolved again.
